project:
  type: website

format: 
  revealjs:
    menu: true
    controls: false
    section-divs: true
    preview-links: true
    embed-resources: true
    transition: slide
    background-transition: fade
    navigation-mode: linear
    email-obfuscation: javascript
    theme: theme.scss
    footer: '**Edward Chick //** Introduction to Object-Oriented Programming **//** 2025-02-28'
    progress: true
    multiplex: false
    scrollable: false
    hide-inactive-cursor: true
    highlight-style: printing
    pause: true
    fig-width: 6
    fig-height: 7
    fig-align: center

editor: source

execute:
  freeze: auto
  echo: true
  warning: false

code-link: true

title-slide-attributes:
    data-background-image: "images/logo.jpg"
    data-background-position: "right 5% bottom 5%"
    data-background-size: "22%"
    data-background-opacity: "1"

from: markdown+emoji

