[project]
name = "introduction-to-oop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "quarto>=0.1.0",
    "scikit-learn>=1.6.1",
]
